### PR TITLE
Faster intersection method

### PR DESCRIPTION
**Pull request by ambs**
Hello

As added in RT, this change makes the code twice faster.
25 minutes to 10 minutes
70 minutes to 30 minutes
in two heavy tasks.

Would be grateful for a new release soon.

### CODE REVIEW

**Comment by ambs** [comment]
Thank you!

**Comment by trendels** [comment]
Thank you for the patch. It seems like I was trying to be a bit too clever with the original implementation.

When sorting the sets by size before filtering, the implementation can be made even faster if sets are large and of different sizes, at the cost of just a little overhead for small sets:

```perl
sub intersection2 {                                                             
    my $class = ref $_[0];                                                      
    my ($a, $b) = $_[0]->size > $_[1]->size ? ($_[0], $_[1]) : ($_[1], $_[0]);  
    return $class->new( grep { exists($a->{$_}) } keys %{$b} );                 
}
```
```
Building the intersection of two sets of size 5 and 10
                 Rate        clone with sorting   no sorting
clone         35223/s           --         -66%         -70%
with sorting 104387/s         196%           --         -10%
no sorting   115993/s         229%          11%           --
```

```
Building the intersection of two sets of size 10 and 100
                Rate        clone   no sorting with sorting
clone         9309/s           --         -70%         -87%
no sorting   31508/s         238%           --         -57%
with sorting 73770/s         692%         134%           --
```

Would this make a difference for your code?

**Comment by ambs** [comment]
In fact, it should not. When I first commented on this I was wrong. I do not have large sets, but a large amount of sets. They are like 5 to 6 elements top.

It might be relevant to have different options. But then, as a Tiny implementation, you might not want to.

**Comment by trendels** [comment]
All right. I've added the version with sorting under a different name, in case someone needs it. The new release is on it's way to CPAN.

**Comment by ambs** [comment]
Thanks for the efficiency \o/

**Pull request merged**
